-   id: matlab-reflow-comments
    name: MATLAB Reflow Comments
    description: Reflow MATLAB comment line(s) to the specified line length
    entry: matlab-reflow-comments
    language: python
    types: [text]
    files: '\.m$'
-   id: invoke-mlint
    name: Invoke mlint
    description: Obtain Code Analyzer messages from mlint
    entry: invoke-mlint
    language: python
    types: [text]
    files: '\.m$'
